
DEFAULT_RADIUS = 1
DEFAULT_GEAR_OFFESET = 0.3
DEFAULT_TWIDTH = 0.3

DEFAULT_ROD_RADIUS = 1
DEFAULT_ROD_LEN = 3

TAG_CATEGORY = "GearCreator"

TAG_GEARNETWORK = "GEARNETWORK"
TAG_GEARCHAIN = "GEARCHAIN"
TAG_GEAR = "GEAR"
TAG_ROD = "ROD"
TAG_CONSTRAINTS_C = "CONSTRAINT_C"

ROD_SUBGROUP = "RODS"

TAG_CONNECT_NEIGHBOUR = "NEIGHBOUR"
TAG_CONNECT_ROD = "CONNECT_ROD"
TAG_CONNECT_CONSTRAINTS_C = "CONNECT_CONSTRAINT_C"