
DEFAULT_RADIUS = 1
DEFAULT_GEAR_OFFESET = 0.3
DEFAULT_TWIDTH = 0.3

DEFAULT_ROD_RADIUS = 1
DEFAULT_ROD_LEN = 3

TAG_CATEGORY = "GearCreator"

TAG_GEARNETWORK = "GEARNETWORK"
TAG_GEARCHAIN = "GEARCHAIN"
TAG_GEAR = "GEAR"
TAG_ROD = "ROD"

ROD_SUBGROUP = "RODS"

TAG_CONNECT_ROD = "LINKED_ROD"
